### ISSUE TITLE
accuracy

### ISSUE THREAD

**Issue by yujialele** [Ylexx/HBPASM#4]
你好，我试着用您的代码跑cub200我发现，自己在finetune 上test集的准确率在60多epoch时就出现过拟合的现象，我想咨询您这是正常现象，还是我的训练存在问题。

**Comment by Ylexx** [comment]
这几个数据集相对来说都比较小，确实会存在一定的过拟合现象，在训练集上很容易拟合到100%；
另外对于细粒度分类这个任务，本身就很容易过拟合，加上数据集的原因，不可避免的存在一定的过拟合现象。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yujialele"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月9日(星期天) 上午10:48
收件人:&nbsp;"Ylexx/HBPASM"<HBPASM@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Ylexx/HBPASM] accuracy (#4)




你好，我试着用您的代码跑cub200我发现，自己在finetune 上test集的准确率在60多epoch时就出现过拟合的现象，我想咨询您这是正常现象，还是我的训练存在问题。

**Comment by yujialele** [comment]
@Ylexx ，谢谢你的回复，我想问一下，train_firststep 中训练集和测试集batchsize的大小和train_fineturn不一致，会对结果产生较大的影响吗？

**Comment by Ylexx** [comment]
会有影响，你可以尝试一下不同的batch_size对你的结果产生的影响。我实验中用的batch_size是
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;first&nbsp; &nbsp; &nbsp;finetune
cub&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 8&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 16
car&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;8&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 8
aircraft&nbsp; &nbsp; &nbsp; &nbsp;8&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 8








------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yujialele"<notifications@github.com&gt;; 
发送时间: 2020年2月9日(星期天) 中午11:06
收件人: "Ylexx/HBPASM"<HBPASM@noreply.github.com&gt;; 
抄送: "贵军"<1115417581@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [Ylexx/HBPASM] accuracy (#4)




@Ylexx ，谢谢你的回复，我想问一下，train_firststep 中训练集和测试集batchsize的大小和train_fineturn不一致，会对结果产生较大的影响吗？

**Comment by yujialele** [comment]
你好，我想问一下，您说train_firststep是只训练fc和all_project层，但是我看到是训练整个网络和train_finetune没有区别。希望您为我解答一下。

**Comment by yujialele** [comment]
@Ylexx , 对不起我之前没有了解过pytorch冻结层以及相关参数训练的知识，在上面妄加揣测train_finetune与train_firststep 二者没有区别，在这里向您表示抱歉。
